spring.datasource.url=jdbc:h2:file:./data/nextandb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}
spring.mvc.welcome-file=static/nextan-service-form.html
app.default-from=eunicetanyongnie@gmail.com
app.finance-emails=${FINANCE_EMAILS:unicorntanyongnie@gmail.com,finance2@nextan.com}
app.staff-emails=${STAFF_EMAILS:janicelav9@gmail.com,tech2@nextan.com,engineer3@nextan.com}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
